### ISSUE TITLE
Media resources with the same name.

### ISSUE THREAD

**Issue by uo265363** [Arquisoft/viadeSpec#36]
As we have now in the specification, the files in the resource folder are stored with the name of the file.
Then if we have 2 files with the same name it's going to give some problems when we try to fetch those files, so I think that we might change that. A solution could be to store resources with uuids (same as we do with routes and comments) and change the media property in route properties as well. The media property could be something like this
`media: [
   {"@id":da34fas749sa3h883j.mp3 , "name": "miAudio"},
   {"@id":pt92as74234a3h5xb3j.mp4 , "name": "miOtroFichero"}
]`

**Comment by PabloCanalSuarez** [comment]
I think this is a really good idea, as it could be interesting to save the name property (or even some **other optional properties** like description, date, etc., that we could discuss). 

Also, the uuid idea seems like something we have ignored in the media files until now. I believe it's really important to save these files also with an uuid rather than its name, just like we do with routes, as you've said.

**Comment by PabloCanalSuarez** [comment]
Added to PR #21
